Repository SE-F24-SP4/semesterproject-4, pull requests merged in 2024-04, with the labels that each got.

#60 Add JavaFX and game processing.
  Common/src/main/java/com/github/sef24sp4/common/data/Coordinates.java
  Common/src/main/java/com/github/sef24sp4/common/data/EntityManager.java
  Common/src/main/java/com/github/sef24sp4/common/interfaces/IEntityManager.java
  Common/src/main/java/com/github/sef24sp4/common/interfaces/IGameSettings.java
  Common/src/main/java/com/github/sef24sp4/common/interfaces/IVector.java
  Common/src/test/java/com/github/sef24sp4/common/interfaces/IVectorTest.java
  Core/pom.xml
  Core/src/main/java/com/github/sef24sp4/core/Main.java
  Core/src/main/java/com/github/sef24sp4/core/game/Game.java
  Core/src/main/java/com/github/sef24sp4/core/game/GameBuilder.java
  Core/src/main/java/com/github/sef24sp4/core/game/GameInput.java
  Core/src/main/java/com/github/sef24sp4/core/game/GameLoop.java
  Core/src/main/java/com/github/sef24sp4/core/game/GameSettings.java
  Core/src/main/java/com/github/sef24sp4/core/game/GraphicsOverlayEntityManager.java
  Core/src/main/java/com/github/sef24sp4/core/interfaces/EntityToGraphicsMapper.java
  Core/src/main/java/com/github/sef24sp4/core/interfaces/IGameProcessor.java
  Core/src/main/java/com/github/sef24sp4/core/interfaces/IGameTick.java
  Core/src/main/java/com/github/sef24sp4/core/interfaces/IGameTickExecutor.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/AnimationTimerTickExecutor.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/EntityToJavaFxMapper.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/JavaFXInputMap.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/JavaFxInputInitializer.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/JavaFxMouseCoordinates.java
  Core/src/main/java/com/github/sef24sp4/core/scenes/GameScene.java
  Core/src/main/java/com/github/sef24sp4/core/scenes/StartMenu.java
  Core/src/main/java/module-info.java
  Core/src/main/resources/com/github/sef24sp4/core/scenes/start-menu.fxml
Labels: enhancement

#68 Defined WeaponSPI Interface
  CommonWeapon/pom.xml
  CommonWeapon/src/main/java/com/github/sef24sp4/common/weapon/CommonWeapon.java
  CommonWeapon/src/main/java/com/github/sef24sp4/common/weapon/WeaponSPI.java
  CommonWeapon/src/main/java/module-info.java
Labels: enhancement

#72 Improve JavaDoc for ICollidableEntity
  Common/src/main/java/com/github/sef24sp4/common/entities/ICollidableEntity.java
Labels: documentation

#57 Implement #10 polygonenemy
  CommonEnemy/pom.xml
  CommonEnemy/src/main/java/com/github/sef24sp4/common/enemy/EnemySPI.java
  CommonEnemy/src/main/java/module-info.java
  PolygonEnemy/pom.xml
  PolygonEnemy/src/main/java/com/github/sef24sp4/polygonenemy/PolygonEnemy.java
  PolygonEnemy/src/main/java/com/github/sef24sp4/polygonenemy/PolygonEnemyControlSystem.java
  PolygonEnemy/src/main/java/com/github/sef24sp4/polygonenemy/PolygonEnemyPlugin.java
  PolygonEnemy/src/main/java/module-info.java
  PolygonEnemy/src/test/java/com/github/sef24sp4/polygonenemy/PolygonEnemyTest.java
Labels: question

#77 Add IEntityManager.removeEntitiesByClass method
  Common/src/main/java/com/github/sef24sp4/common/interfaces/IEntityManager.java
  PolygonEnemy/src/main/java/com/github/sef24sp4/polygonenemy/PolygonEnemyPlugin.java
Labels: enhancement

#75 Make Coordinates Cloneable
  Common/src/main/java/com/github/sef24sp4/common/data/Coordinates.java
  Common/src/test/java/com/github/sef24sp4/common/data/CoordinatesTest.java
Labels: enhancement

#76 Fix #73: Redefine return value for infinite ammunition
  CommonWeapon/src/main/java/com/github/sef24sp4/common/weapon/WeaponSPI.java
Labels: documentation

#63 Player/02 implementing player
  Player/pom.xml
  Player/src/main/java/com/github/sef24sp4/player/Player.java
  Player/src/main/java/com/github/sef24sp4/player/PlayerControl.java
  Player/src/main/java/com/github/sef24sp4/player/PlayerPlugin.java
  Player/src/main/java/module-info.java
Labels: enhancement

#71 CommonAI interface
  CommonAI/pom.xml
  CommonAI/src/main/java/com/github/sef24sp4/common/ai/IPathfindingProvider.java
  CommonAI/src/main/java/module-info.java
Labels: enhancement

#79 Fix mouse input initialisation
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/JavaFxInputInitializer.java
Labels: bug

#80 Update player model
  Player/src/main/java/com/github/sef24sp4/player/Player.java
Labels: enhancement

#92 Add generic interface for AI to query map for navigation
  CommonAI/src/main/java/com/github/sef24sp4/common/ai/map/Map.java
  CommonAI/src/main/java/com/github/sef24sp4/common/ai/map/MapNode.java
Labels: enhancement

#91 Player heal()
  Player/src/main/java/com/github/sef24sp4/player/Player.java
Labels: enhancement

#97 Use more specific return types for vector methods
  Common/src/main/java/com/github/sef24sp4/common/vector/Coordinates.java
  Common/src/main/java/com/github/sef24sp4/common/vector/IVector.java
Labels: enhancement

#98 Add query methods for querying entities of a certain ElementType
  Common/src/main/java/com/github/sef24sp4/common/entities/CommonEntity.java
  Common/src/main/java/com/github/sef24sp4/common/entities/ICollidableEntity.java
  Common/src/main/java/com/github/sef24sp4/common/entities/IEntity.java
  Common/src/main/java/com/github/sef24sp4/common/interfaces/IEntityManager.java
  Common/src/test/java/com/github/sef24sp4/common/data/EntityManagerTest.java
  Common/src/test/java/com/github/sef24sp4/common/entities/CommonEntityTest.java
Labels: enhancement

#93 Polygon enemy/11 enemy ai
  PolygonEnemy/pom.xml
  PolygonEnemy/src/main/java/com/github/sef24sp4/polygonenemy/PolygonEnemy.java
  PolygonEnemy/src/main/java/com/github/sef24sp4/polygonenemy/PolygonEnemyControlSystem.java
  PolygonEnemy/src/main/java/module-info.java
Labels: enhancement

#88 Common item/interface
  CommonItem/pom.xml
  CommonItem/src/main/java/com/github/sef24sp4/common/item/CommonItem.java
  CommonItem/src/main/java/com/github/sef24sp4/common/item/ItemRarity.java
  CommonItem/src/main/java/com/github/sef24sp4/common/item/ItemSPI.java
  CommonItem/src/main/java/com/github/sef24sp4/common/item/WeaponItem.java
  CommonItem/src/main/java/module-info.java
Labels: enhancement
