Repository SE-F24-SP4/semesterproject-4, pull requests merged in 2024-05, with the labels that each got.

#104 Add method for check coordinates is within MapNode
  CommonAI/src/main/java/com/github/sef24sp4/common/ai/map/Map.java
  CommonAI/src/main/java/com/github/sef24sp4/common/ai/map/MapNode.java
Labels: enhancement

#105 Implementing Health Item
  HealthItem/pom.xml
  HealthItem/src/main/java/com/github/sef24sp4/healthitem/HealthItem.java
  HealthItem/src/main/java/com/github/sef24sp4/healthitem/HealthItemPlugin.java
  HealthItem/src/main/java/com/github/sef24sp4/healthitem/HealthItemProvider.java
  HealthItem/src/main/java/module-info.java
  HealthItem/src/test/java/com/github/sef24sp4/healthitem/HealthItemTest.java
  Player/src/main/java/com/github/sef24sp4/player/Player.java
Labels: enhancement

#111 Vector: Add getOrthogonalVector and getNewVectorWithAngle methods
  Common/src/main/java/com/github/sef24sp4/common/vector/BasicVector.java
  Common/src/main/java/com/github/sef24sp4/common/vector/IVector.java
  Common/src/test/java/com/github/sef24sp4/common/vector/IVectorTest.java
Labels: enhancement

#113 Add additional methods to MapNode
  CommonAI/src/main/java/com/github/sef24sp4/common/ai/map/MapNode.java
  CommonAI/src/main/java/com/github/sef24sp4/common/ai/map/NotAdjacentNodeException.java
Labels: documentation, enhancement

#106 Implementing Speed Item
  CommonItem/src/main/java/com/github/sef24sp4/common/item/itemtypes/ISpeedItem.java
  ItemPack/pom.xml
  ItemPack/src/main/java/com/github/sef24sp4/itempack/ItemPackPlugin.java
  ItemPack/src/main/java/com/github/sef24sp4/itempack/SpeedItem.java
  ItemPack/src/main/java/com/github/sef24sp4/itempack/SpeedItemProvider.java
  ItemPack/src/main/java/module-info.java
  ItemPack/src/test/java/com/github/sef24sp4/itempack/SpeedItemTest.java
  Player/pom.xml
  Player/src/main/java/com/github/sef24sp4/player/Player.java
  Player/src/main/java/com/github/sef24sp4/player/PlayerControl.java
  Player/src/main/java/com/github/sef24sp4/player/SpeedControl.java
  Player/src/main/java/module-info.java
Labels: enhancement

#108 Player Tests
  Player/src/main/java/com/github/sef24sp4/player/Player.java
  Player/src/test/java/com/github/sef24sp4/player/PlayerTest.java
  Player/src/test/java/com/github/sef24sp4/player/SpeedControlTest.java
Labels: enhancement

#115 Fix game not keeping fullscreen on scene change
  Core/src/main/java/com/github/sef24sp4/core/Main.java
  Core/src/main/java/com/github/sef24sp4/core/game/Game.java
  Core/src/main/java/com/github/sef24sp4/core/game/GameBuilder.java
  Core/src/main/java/com/github/sef24sp4/core/game/GameInput.java
  Core/src/main/java/com/github/sef24sp4/core/game/GameLoop.java
  Core/src/main/java/com/github/sef24sp4/core/game/GameSettings.java
  Core/src/main/java/com/github/sef24sp4/core/interfaces/EntityToGraphicsMapper.java
  Core/src/main/java/com/github/sef24sp4/core/interfaces/IGameTick.java
  Core/src/main/java/com/github/sef24sp4/core/interfaces/IGameTickExecutor.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/AnimationTimerTickExecutor.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/EntityToJavaFxMapper.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/JavaFXInputMap.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/JavaFxInputInitializer.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/JavaFxMouseCoordinates.java
  Core/src/main/java/com/github/sef24sp4/core/scenes/GameScene.java
  Core/src/main/java/com/github/sef24sp4/core/scenes/StartMenu.java
  Core/src/main/resources/com/github/sef24sp4/core/scenes/start-menu.fxml
Labels: bug, enhancement

#117 Defined MapProvider interface
  CommonAI/src/main/java/com/github/sef24sp4/common/ai/map/MapProvider.java
  CommonAI/src/main/java/module-info.java
Labels: enhancement

#118 Add Label support
  Common/src/main/java/com/github/sef24sp4/common/graphics/label/Label.java
  Common/src/main/java/com/github/sef24sp4/common/graphics/label/LabelFactory.java
  Common/src/main/java/com/github/sef24sp4/common/graphics/label/LabelProvider.java
  Common/src/main/java/module-info.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/JavaFxLabel.java
  Core/src/main/java/com/github/sef24sp4/core/javafxbindings/JavaFxLabelProvider.java
  Core/src/main/java/com/github/sef24sp4/core/scenes/GameScene.java
  Core/src/main/java/module-info.java
Labels: enhancement

#120 Add LabelFactory.create with font size
  Common/src/main/java/com/github/sef24sp4/common/graphics/label/LabelFactory.java
Labels: enhancement

#86 Weapon pack/machine gun
  BaseWeapon/src/main/java/com/github/sef24sp4/baseweapon/BaseProjectile.java
  BaseWeapon/src/main/java/com/github/sef24sp4/baseweapon/BaseProjectilePlugin.java
  BaseWeapon/src/main/java/com/github/sef24sp4/baseweapon/BaseWeapon.java
  BaseWeapon/src/main/java/com/github/sef24sp4/baseweapon/ProjectileControlSystem.java
  WeaponPack/pom.xml
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/AbstractBulletControlSystem.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/AbstractProjectile.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/AbstractWeapon.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/AbstractWeaponItem.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/BulletPlugin.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/machinegun/MachineGun.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/machinegun/MachineGunBullet.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/machinegun/MachineGunBulletControlSystem.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/machinegun/MachineGunItem.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/machinegun/MachineGunItemProvider.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/shotgun/ShotGun.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/shotgun/ShotGunBullet.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/shotgun/ShotGunBulletControlSystem.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/shotgun/ShotGunItem.java
  WeaponPack/src/main/java/com/github/sef24sp4/weaponpack/shotgun/ShotGunItemProvider.java
  WeaponPack/src/main/java/module-info.java
Labels: enhancement

#122 Add GameSettingsLoader with static method for loading IGameSettings
  Common/src/main/java/com/github/sef24sp4/common/interfaces/GameSettingsLoader.java
  Common/src/main/java/module-info.java
  CommonAI/src/main/java/com/github/sef24sp4/common/ai/map/MapProvider.java
  Core/src/main/java/com/github/sef24sp4/core/game/GameSettingsProvider.java
  Core/src/main/java/com/github/sef24sp4/core/scenes/GameScene.java
  Core/src/main/java/module-info.java
Labels: enhancement

#119 Implemented ability to shoot with different weapons
  Player/src/main/java/com/github/sef24sp4/player/Player.java
  Player/src/main/java/com/github/sef24sp4/player/PlayerControl.java
  Player/src/main/java/com/github/sef24sp4/player/PlayerPlugin.java
  Player/src/main/java/com/github/sef24sp4/player/SpeedControl.java
  Player/src/test/java/com/github/sef24sp4/player/PlayerTest.java
Labels: enhancement

#109 16 wave generation/main
  CommonEnemy/src/main/java/com/github/sef24sp4/common/enemy/CommonEnemy.java
  CommonEnemy/src/main/java/com/github/sef24sp4/common/enemy/EnemyRole.java
  CommonEnemy/src/main/java/com/github/sef24sp4/common/enemy/EnemySPI.java
  PolygonEnemy/src/main/java/com/github/sef24sp4/polygonenemy/PolygonEnemy.java
  PolygonEnemy/src/main/java/com/github/sef24sp4/polygonenemy/PolygonEnemyControlSystem.java
  PolygonEnemy/src/main/java/com/github/sef24sp4/polygonenemy/PolygonEnemyPlugin.java
  PolygonEnemy/src/main/java/module-info.java
  WaveManager/pom.xml
  WaveManager/src/main/java/com/github/sef24sp4/wavemanager/IWaveManager.java
  WaveManager/src/main/java/com/github/sef24sp4/wavemanager/WaveControlSystem.java
  WaveManager/src/main/java/com/github/sef24sp4/wavemanager/WaveManager.java
  WaveManager/src/main/java/com/github/sef24sp4/wavemanager/WaveStatus.java
  WaveManager/src/main/java/module-info.java
Labels: documentation, enhancement

#121 Implemented labels for Player
  Player/src/main/java/com/github/sef24sp4/player/Player.java
  Player/src/main/java/com/github/sef24sp4/player/PlayerControl.java
  Player/src/main/java/com/github/sef24sp4/player/PlayerPlugin.java
Labels: enhancement

#124 Polygon drops items
  CommonItem/src/main/java/module-info.java
  PolygonEnemy/pom.xml
  PolygonEnemy/src/main/java/com/github/sef24sp4/polygonenemy/PolygonEnemy.java
  PolygonEnemy/src/main/java/module-info.java
Labels: enhancement

#123 Add cooldown to player damage
  Player/src/main/java/com/github/sef24sp4/player/Player.java
  Player/src/test/java/com/github/sef24sp4/player/PlayerTest.java
Labels: enhancement

#125 Implement game stopping when player dies.
  Common/src/main/java/com/github/sef24sp4/common/interfaces/IGameSettings.java
  Core/src/main/java/com/github/sef24sp4/core/game/GameSettings.java
  Core/src/main/java/com/github/sef24sp4/core/scenes/GameScene.java
  Player/src/main/java/com/github/sef24sp4/player/Player.java
  Player/src/test/java/com/github/sef24sp4/player/PlayerTest.java
Labels: enhancement

#126 Player/speed fix
  Player/src/main/java/com/github/sef24sp4/player/SpeedControl.java
Labels: enhancement
